### ISSUE TITLE
Sequential download option

### ISSUE THREAD

**Issue by midenok** [midenok/qBittorrent#1]
## Task
Add to `AddNewTorrentDialog::accept()`; `WebApplication::action_command_download()`:
```c++
const Preferences* const pref = Preferences::instance();
params.sequential = pref->sequentialDownload();
```

### `AddTorrentData` constructed (from native UI)
```c++
#0 BitTorrent::AddTorrentData::AddTorrentData (this=0x7fff275315c8, params=...) at /home/midenok/src/qbittorrent/src/base/bittorrent/torrenthandle.cpp:84
#1 0x00000000004808d2 in BitTorrent::Session::addTorrent (this=0x12db000, source="592ac0b61824d39900e6c136ea9e6cd060a41d5d", params=...) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:1602
#2 0x00000000005879be in AddNewTorrentDialog::accept (this=0x14fbc40) at /home/midenok/src/qbittorrent/src/gui/addnewtorrentdialog.cpp:661
#3 0x00000000006347a0 in AddNewTorrentDialog::qt_static_metacall (_o=0x14fbc40, _c=QMetaObject::InvokeMetaMethod, _id=14, _a=0x7fff27531ab0) at src/gui/qbt_gui_automoc.dir/moc_addnewtorrentd_JCUUSEANITGQCR.cpp:150
#4 0x00007ff5544ed8e5 in QMetaObject::activate (sender=sender@entry=0x1a16ce0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x0) at kernel/qobject.cpp:3766
#5 0x00007ff5544edfb7 in QMetaObject::activate (sender=sender@entry=0x1a16ce0, m=m@entry=0x7ff555b96fe0 <QDialogButtonBox::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x0) at kernel/qobject.cpp:3628
#6 0x00007ff555690863 in QDialogButtonBox::accepted (this=this@entry=0x1a16ce0) at .moc/moc_qdialogbuttonbox.cpp:282
#7 0x00007ff555690e80 in QDialogButtonBoxPrivate::_q_handleButtonClicked (this=<optimized out>) at widgets/qdialogbuttonbox.cpp:860
#8 0x00007ff5544ed8e5 in QMetaObject::activate (sender=sender@entry=0x14b1e50, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7fff27531c40) at kernel/qobject.cpp:3766
#9 0x00007ff5544edfb7 in QMetaObject::activate (sender=sender@entry=0x14b1e50, m=m@entry=0x7ff555b95840 <QAbstractButton::staticMetaObject>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7fff27531c40) at kernel/qobject.cpp:3628
#10 0x00007ff55567f572 in QAbstractButton::clicked (this=this@entry=0x14b1e50, _t1=<optimized out>) at .moc/moc_qabstractbutton.cpp:309
#11 0x00007ff55567f78a in QAbstractButtonPrivate::emitClicked (this=0x1696080) at widgets/qabstractbutton.cpp:410
#12 0x00007ff555680b6a in QAbstractButtonPrivate::click (this=0x1696080) at widgets/qabstractbutton.cpp:403
#13 0x00007ff555680d54 in QAbstractButton::mouseReleaseEvent (this=0x14b1e50, e=0x7fff275321a0) at widgets/qabstractbutton.cpp:1006
#14 0x00007ff555503dc8 in QWidget::event (this=0x14b1e50, event=0x7fff275321a0) at kernel/qwidget.cpp:9178
#15 0x00007ff5554c346c in QApplicationPrivate::notify_helper (this=this@entry=0x1237710, receiver=receiver@entry=0x14b1e50, e=e@entry=0x7fff275321a0) at kernel/qapplication.cpp:3717
#16 0x00007ff5554cb28f in QApplication::notify (this=<optimized out>, receiver=0x14b1e50, e=0x7fff275321a0) at kernel/qapplication.cpp:3193
#17 0x000000000045d6e8 in Application::notify (this=0x1236de0, receiver=0x14b1e50, event=0x7fff275321a0) at /home/midenok/src/qbittorrent/src/app/application.cpp:505
#18 0x00007ff5544bede8 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x14b1e50, event=event@entry=0x7fff275321a0) at kernel/qcoreapplication.cpp:1018
#19 0x00007ff5554ca262 in QCoreApplication::sendEvent (event=<optimized out>, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:233
#20 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0x14b1e50, event=event@entry=0x7fff275321a0, alienWidget=alienWidget@entry=0x14b1e50, nativeWidget=0x14fbc40, buttonDown=buttonDown@entry=0x7ff555bb27c0 <qt_button_down>, lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:2699
#21 0x00007ff55551e94b in QWidgetWindow::handleMouseEvent (this=this@entry=0x1a0c6a0, event=event@entry=0x7fff27532650) at kernel/qwidgetwindow.cpp:621
#22 0x00007ff555520fba in QWidgetWindow::event (this=0x1a0c6a0, event=0x7fff27532650) at kernel/qwidgetwindow.cpp:243
#23 0x00007ff5554c346c in QApplicationPrivate::notify_helper (this=this@entry=0x1237710, receiver=receiver@entry=0x1a0c6a0, e=e@entry=0x7fff27532650) at kernel/qapplication.cpp:3717
#24 0x00007ff5554cad34 in QApplication::notify (this=0x1236de0, receiver=0x1a0c6a0, e=0x7fff27532650) at kernel/qapplication.cpp:3476
#25 0x000000000045d6e8 in Application::notify (this=0x1236de0, receiver=0x1a0c6a0, event=0x7fff27532650) at /home/midenok/src/qbittorrent/src/app/application.cpp:505
#26 0x00007ff5544bede8 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x1a0c6a0, event=event@entry=0x7fff27532650) at kernel/qcoreapplication.cpp:1018
#27 0x00007ff554d07f43 in QCoreApplication::sendSpontaneousEvent (event=0x7fff27532650, receiver=0x1a0c6a0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:236
#28 QGuiApplicationPrivate::processMouseEvent (e=0x1b27280) at kernel/qguiapplication.cpp:1949
#29 0x00007ff554d09a25 in QGuiApplicationPrivate::processWindowSystemEvent (e=e@entry=0x1b27280) at kernel/qguiapplication.cpp:1733
#30 0x00007ff554ce1cab in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:939
#31 0x00007ff54b8f05a0 in userEventSourceDispatch (source=source@entry=0x127c290) at qeventdispatcher_glib.cpp:77
#32 0x00007ff551ad7fb7 in g_main_dispatch (context=0x7ff544004fc0) at ../../../../glib/gmain.c:3148
#33 g_main_context_dispatch (context=context@entry=0x7ff544004fc0) at ../../../../glib/gmain.c:3813
#34 0x00007ff551ad81f0 in g_main_context_iterate (context=context@entry=0x7ff544004fc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../../glib/gmain.c:3886
#35 0x00007ff551ad827c in g_main_context_iteration (context=0x7ff544004fc0, may_block=may_block@entry=1) at ../../../../glib/gmain.c:3947
#36 0x00007ff55451747f in QEventDispatcherGlib::processEvents (this=0x126ea90, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#37 0x00007ff5544bce3a in QEventLoop::exec (this=this@entry=0x7fff27532a00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#38 0x00007ff5544c5da4 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1291
#39 0x000000000045d6a3 in Application::exec (this=0x1236de0, params=empty QStringList<QString>) at /home/midenok/src/qbittorrent/src/app/application.cpp:450
#40 0x00000000004679f8 in main (argc=1, argv=0x7fff27532e38) at /home/midenok/src/qbittorrent/src/app/main.cpp:304
```
#### or from Web UI
```c++
#0 BitTorrent::AddTorrentData::AddTorrentData (this=0x7fff27531748, params=...) at /home/midenok/src/qbittorrent/src/base/bittorrent/torrenthandle.cpp:84
#1 0x00000000004808d2 in BitTorrent::Session::addTorrent (this=0x12db000, source="magnet:?xt=urn:btih:592ac0b61824d39900e6c136ea9e6cd060a41d5d&dn=rutor.info_%D0%9D%D0%B0%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B8%D0%B9+%D0%94%D0%B5%D1%82%D0%B5%D0%BA%D1%82%D0%B8%D0%B2+%2F+True+Detective+%5BS02%5D+%282015%29+HDTVRip+720p+%D0%BE%D1%82+qqss44+%7C+Amedia&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce", params=...) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:1602
#2 0x000000000066670a in WebApplication::action_command_download (this=0x16482b0) at /home/midenok/src/qbittorrent/src/webui/webapplication.cpp:427
#3 0x0000000000673dc9 in WebApplication::doProcessRequest (this=0x16482b0) at /home/midenok/src/qbittorrent/src/webui/webapplication.cpp:861
#4 0x000000000065a1b2 in AbstractWebApplication::processRequest (this=0x16482b0, request=..., env=...) at /home/midenok/src/qbittorrent/src/webui/abstractwebapplication.cpp:137
#5 0x000000000065b21b in non-virtual thunk to AbstractWebApplication::processRequest(Http::Request const&, Http::Environment const&) () at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1408
#6 0x000000000053f4d1 in Http::Connection::read (this=0x1e14c60) at /home/midenok/src/qbittorrent/src/base/http/connection.cpp:82
#7 0x000000000052c981 in Http::Connection::qt_static_metacall (_o=0x1e14c60, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fff27532470) at /home/midenok/src/qbittorrent/build/src/base/qbt_base_automoc.dir/moc_connection_3IB65OGZQL6FQB.cpp:71
#8 0x00007ff5544ed8e5 in QMetaObject::activate (sender=sender@entry=0x2064fe0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3766
#9 0x00007ff5544edfb7 in QMetaObject::activate (sender=sender@entry=0x2064fe0, m=m@entry=0x7ff5549738e0 <QIODevice::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3628
#10 0x00007ff5543e2090 in QIODevice::readyRead (this=this@entry=0x2064fe0) at .moc/moc_qiodevice.cpp:186
#11 0x00007ff555ecf593 in QAbstractSocketPrivate::emitReadyRead (this=this@entry=0x7ff53001be80, channel=channel@entry=0) at socket/qabstractsocket.cpp:1312
#12 0x00007ff555ecf644 in QAbstractSocketPrivate::canReadNotification (this=0x7ff53001be80) at socket/qabstractsocket.cpp:732
#13 0x00007ff555ee1d21 in QReadNotifier::event (this=<optimized out>, e=<optimized out>) at socket/qnativesocketengine.cpp:1273
#14 0x00007ff5554c346c in QApplicationPrivate::notify_helper (this=this@entry=0x1237710, receiver=receiver@entry=0x7ff53004c4c0, e=e@entry=0x7fff275327e0) at kernel/qapplication.cpp:3717
#15 0x00007ff5554cad34 in QApplication::notify (this=0x1236de0, receiver=0x7ff53004c4c0, e=0x7fff275327e0) at kernel/qapplication.cpp:3476
#16 0x000000000045d6e8 in Application::notify (this=0x1236de0, receiver=0x7ff53004c4c0, event=0x7fff275327e0) at /home/midenok/src/qbittorrent/src/app/application.cpp:505
#17 0x00007ff5544bede8 in QCoreApplication::notifyInternal2 (receiver=0x7ff53004c4c0, event=event@entry=0x7fff275327e0) at kernel/qcoreapplication.cpp:1018
#18 0x00007ff5545180dd in QCoreApplication::sendEvent (event=0x7fff275327e0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:233
#19 socketNotifierSourceDispatch (source=source@entry=0x1276300) at kernel/qeventdispatcher_glib.cpp:106
#20 0x00007ff551ad7fb7 in g_main_dispatch (context=0x7ff544004fc0) at ../../../../glib/gmain.c:3148
#21 g_main_context_dispatch (context=context@entry=0x7ff544004fc0) at ../../../../glib/gmain.c:3813
#22 0x00007ff551ad81f0 in g_main_context_iterate (context=context@entry=0x7ff544004fc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../../glib/gmain.c:3886
#23 0x00007ff551ad827c in g_main_context_iteration (context=0x7ff544004fc0, may_block=may_block@entry=1) at ../../../../glib/gmain.c:3947
#24 0x00007ff55451747f in QEventDispatcherGlib::processEvents (this=0x126ea90, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#25 0x00007ff5544bce3a in QEventLoop::exec (this=this@entry=0x7fff27532a00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#26 0x00007ff5544c5da4 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1291
#27 0x000000000045d6a3 in Application::exec (this=0x1236de0, params=empty QStringList<QString>) at /home/midenok/src/qbittorrent/src/app/application.cpp:450
#28 0x00000000004679f8 in main (argc=1, argv=0x7fff27532e38) at /home/midenok/src/qbittorrent/src/app/main.cpp:304
```
### `TorrentHandle` constructed
```c++
#0 BitTorrent::TorrentHandle::TorrentHandle (this=0x178d3d0, session=0x12db000, nativeHandle=..., data=...) at /home/midenok/src/qbittorrent/src/base/bittorrent/torrenthandle.cpp:207
#1 0x0000000000481391 in BitTorrent::Session::createTorrentHandle (this=0x12db000, nativeHandle=...) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3310
#2 0x000000000048b4d9 in BitTorrent::Session::handleAddTorrentAlert (this=0x12db000, p=0x7ff530042540) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3379
#3 0x000000000048a674 in BitTorrent::Session::handleAlert (this=0x12db000, a=0x7ff530042540) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3254
#4 0x000000000048a3d3 in BitTorrent::Session::readAlerts (this=0x12db000) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3216
#5 0x000000000052a7e8 in BitTorrent::Session::qt_static_metacall (_o=0x12db000, _c=QMetaObject::InvokeMetaMethod, _id=33, _a=0x7ff53001ce70) at /home/midenok/src/qbittorrent/build/src/base/qbt_base_automoc.dir/moc_session_V3MD6UR47GUQY7.cpp:303
#6 0x00007ff5544ee452 in QObject::event (this=0x12db000, e=<optimized out>) at kernel/qobject.cpp:1246
#7 0x00007ff5554c346c in QApplicationPrivate::notify_helper (this=this@entry=0x1237710, receiver=receiver@entry=0x12db000, e=e@entry=0x7ff53005c810) at kernel/qapplication.cpp:3717
#8 0x00007ff5554cad34 in QApplication::notify (this=0x1236de0, receiver=0x12db000, e=0x7ff53005c810) at kernel/qapplication.cpp:3476
#9 0x000000000045d6e8 in Application::notify (this=0x1236de0, receiver=0x12db000, event=0x7ff53005c810) at /home/midenok/src/qbittorrent/src/app/application.cpp:505
#10 0x00007ff5544bede8 in QCoreApplication::notifyInternal2 (receiver=0x12db000, event=event@entry=0x7ff53005c810) at kernel/qcoreapplication.cpp:1018
#11 0x00007ff5544c155d in QCoreApplication::sendEvent (event=0x7ff53005c810, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:233
#12 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x1235a60) at kernel/qcoreapplication.cpp:1678
#13 0x00007ff5544c1ae8 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1532
#14 0x00007ff554517e53 in postEventSourceDispatch (s=s@entry=0x127b440) at kernel/qeventdispatcher_glib.cpp:276
#15 0x00007ff551ad7fb7 in g_main_dispatch (context=0x7ff544004fc0) at ../../../../glib/gmain.c:3148
#16 g_main_context_dispatch (context=context@entry=0x7ff544004fc0) at ../../../../glib/gmain.c:3813
#17 0x00007ff551ad81f0 in g_main_context_iterate (context=context@entry=0x7ff544004fc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../../glib/gmain.c:3886
#18 0x00007ff551ad827c in g_main_context_iteration (context=0x7ff544004fc0, may_block=may_block@entry=1) at ../../../../glib/gmain.c:3947
#19 0x00007ff55451747f in QEventDispatcherGlib::processEvents (this=0x126ea90, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#20 0x00007ff5544bce3a in QEventLoop::exec (this=this@entry=0x7fff27532a00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#21 0x00007ff5544c5da4 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1291
#22 0x000000000045d6a3 in Application::exec (this=0x1236de0, params=empty QStringList<QString>) at /home/midenok/src/qbittorrent/src/app/application.cpp:450
#23 0x00000000004679f8 in main (argc=1, argv=0x7fff27532e38) at /home/midenok/src/qbittorrent/src/app/main.cpp:304
```
#### Sequential is copied from `AddTorrentData` in `TorrentHandle::TorrentHandle()`
```c++
    if (!data.resumed)
        setSequentialDownload(data.sequential);
```

**Comment by midenok** [comment]
Similar to https://github.com/qbittorrent/qBittorrent/pull/7453
