### ISSUE TITLE
Unfriendly lost focus when Torrent status switches from Active to Inactive

### ISSUE THREAD

**Issue by midenok** [midenok/qBittorrent#3]
Issue https://github.com/qbittorrent/qBittorrent/issues/7162

**Comment by midenok** [comment]
## StatusFiltersWidget
<img src="https://user-images.githubusercontent.com/3307037/34653401-53d8baee-f3fc-11e7-8960-16a0a2d11968.png" width=150>

## CategoryFilterWidget
<img src="https://user-images.githubusercontent.com/3307037/34653194-d6313bae-f3f9-11e7-8fab-9446e1494f0f.png" width=150>

## TransferListWidget
<img src="https://user-images.githubusercontent.com/3307037/34653298-1782e89a-f3fb-11e7-9d42-1b00b5a080d4.png">

**Comment by midenok** [comment]
## `StatusFiltersWidget` item activated
### 1.
```c++
#0 TransferListWidget::currentChanged (this=0x197ab70, current=...) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:886
#1 0x000000000063aba1 in TransferListWidget::qt_static_metacall (_o=0x197ab70, _c=QMetaObject::InvokeMetaMethod, _id=37, _a=0x7ffc5d31f730) at src/gui/qbt_gui_automoc.dir/moc_transferlistwi_OC27T367ACJHOU.cpp:284
#2 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18215a0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d31f730) at kernel/qobject.cpp:3766
#3 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18215a0, m=m@entry=0x7fed286979e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d31f730) at kernel/qobject.cpp:3628
#4 0x00007fed2818cf3a in QItemSelectionModel::currentChanged (this=this@entry=0x18215a0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#5 0x00007fed28193469 in QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved (this=0x18505b0, parent=..., start=0, end=11) at itemmodels/qitemselectionmodel.cpp:736
#6 0x00007fed28196029 in QItemSelectionModel::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qitemselectionmodel.cpp:264
#7 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x19452e0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=11, argv=argv@entry=0x7ffc5d31fa60) at kernel/qobject.cpp:3766
#8 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x19452e0, m=m@entry=0x7fed286976a0 <QAbstractItemModel::staticMetaObject>, local_signal_index=local_signal_index@entry=11, argv=argv@entry=0x7ffc5d31fa60) at kernel/qobject.cpp:3628
#9 0x00007fed2817c2be in QAbstractItemModel::rowsAboutToBeRemoved (this=this@entry=0x19452e0, _t1=..., _t2=<optimized out>, _t2@entry=0, _t3=<optimized out>, _t3@entry=11, _t4=...) at .moc/moc_qabstractitemmodel.cpp:610
#10 0x00007fed2818321b in QAbstractItemModel::beginRemoveRows (this=0x19452e0, parent=..., first=0, last=11) at itemmodels/qabstractitemmodel.cpp:2746
#11 0x00007fed281a7b65 in QSortFilterProxyModelPrivate::remove_proxy_interval (emit_signal=true, orient=Qt::Vertical, proxy_parent=..., proxy_end=11, proxy_start=0, proxy_to_source=QVector<int> = {...}, source_to_proxy=QVector<int> = {...}, this=0x1850050) at itemmodels/qsortfilterproxymodel.cpp:584
#12 QSortFilterProxyModelPrivate::remove_source_items (this=this@entry=0x1850050, source_to_proxy=QVector<int> = {...}, proxy_to_source=QVector<int> = {...}, source_items=QVector<int> = {...}, source_parent=..., orient=orient@entry=Qt::Vertical, emit_signal=true) at itemmodels/qsortfilterproxymodel.cpp:565
#13 0x00007fed281a80c2 in QSortFilterProxyModelPrivate::handle_filter_changed (this=this@entry=0x1850050, source_to_proxy=QVector<int> = {...}, proxy_to_source=QVector<int> = {...}, source_parent=..., orient=orient@entry=Qt::Vertical) at itemmodels/qsortfilterproxymodel.cpp:1149
#14 0x00007fed281a8439 in QSortFilterProxyModelPrivate::filter_changed (this=0x1850050, source_parent=...) at itemmodels/qsortfilterproxymodel.cpp:1082
#15 0x00007fed281a8c9a in QSortFilterProxyModel::invalidateFilter() () at itemmodels/qsortfilterproxymodel.cpp:2545
#16 0x0000000000656552 in TransferListSortModel::setStatusFilter (this=0x19452e0, filter=TorrentFilter::Downloading) at /home/midenok/src/qbittorrent/src/gui/transferlistsortmodel.cpp:47
#17 0x000000000062ee0c in TransferListWidget::applyStatusFilter (this=0x197ab70, f=1) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:914
#18 0x000000000061e1ef in StatusFiltersWidget::applyFilter (this=0x18712d0, row=1) at /home/midenok/src/qbittorrent/src/gui/transferlistfilterswidget.cpp:174
#19 0x000000000063998c in FiltersBase::qt_static_metacall (_o=0x18712d0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7ffc5d320080) at src/gui/qbt_gui_automoc.dir/moc_transferlistfi_HU55MXOLBACKX2.cpp:92
#20 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18712d0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=8, argv=argv@entry=0x7ffc5d320080) at kernel/qobject.cpp:3766
#21 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18712d0, m=m@entry=0x7fed298c6260 <QListWidget::staticMetaObject>, local_signal_index=local_signal_index@entry=8, argv=argv@entry=0x7ffc5d320080) at kernel/qobject.cpp:3628
#22 0x00007fed29485211 in QListWidget::currentRowChanged (this=this@entry=0x18712d0, _t1=<optimized out>) at .moc/moc_qlistwidget.cpp:411
#23 0x00007fed29485b92 in QListWidgetPrivate::_q_emitCurrentItemChanged (this=<optimized out>, current=..., previous=...) at itemviews/qlistwidget.cpp:1128
#24 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18aa7b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d320210) at kernel/qobject.cpp:3766
#25 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18aa7b0, m=m@entry=0x7fed286979e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d320210) at kernel/qobject.cpp:3628
#26 0x00007fed2818cf3a in QItemSelectionModel::currentChanged (this=this@entry=0x18aa7b0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#27 0x00007fed2818d22e in QItemSelectionModel::setCurrentIndex (this=this@entry=0x18aa7b0, index=..., command=..., command@entry=...) at itemmodels/qitemselectionmodel.cpp:1414
#28 0x00007fed29431bac in QAbstractItemView::mousePressEvent (this=0x18712d0, event=<optimized out>) at itemviews/qabstractitemview.cpp:1788
#29 0x00007fed2922671f in QWidget::event (this=this@entry=0x18712d0, event=event@entry=0x7ffc5d3209e0) at kernel/qwidget.cpp:8794
```
 #### Important:
```c++
#16 0x0000000000656552 in TransferListSortModel::setStatusFilter (this=0x19452e0, filter=TorrentFilter::Downloading) at /home/midenok/src/qbittorrent/src/gui/transferlistsortmodel.cpp:47
#17 0x000000000062ee0c in TransferListWidget::applyStatusFilter (this=0x197ab70, f=1) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:914
#18 0x000000000061e1ef in StatusFiltersWidget::applyFilter (this=0x18712d0, row=1) at /home/midenok/src/qbittorrent/src/gui/transferlistfilterswidget.cpp:174
```
### 2.
```c++
#0 TransferListWidget::currentChanged (this=0x197ab70, current=...) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:886
#1 0x000000000063aba1 in TransferListWidget::qt_static_metacall (_o=0x197ab70, _c=QMetaObject::InvokeMetaMethod, _id=37, _a=0x7ffc5d31fcb0) at src/gui/qbt_gui_automoc.dir/moc_transferlistwi_OC27T367ACJHOU.cpp:284
#2 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18215a0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d31fcb0) at kernel/qobject.cpp:3766
#3 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18215a0, m=m@entry=0x7fed286979e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d31fcb0) at kernel/qobject.cpp:3628
#4 0x00007fed2818cf3a in QItemSelectionModel::currentChanged (this=this@entry=0x18215a0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#5 0x00007fed2818d22e in QItemSelectionModel::setCurrentIndex (this=0x18215a0, index=..., command=...) at itemmodels/qitemselectionmodel.cpp:1414
#6 0x000000000062f0ba in TransferListWidget::applyStatusFilter (this=0x197ab70, f=1) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:918
#7 0x000000000061e1ef in StatusFiltersWidget::applyFilter (this=0x18712d0, row=1) at /home/midenok/src/qbittorrent/src/gui/transferlistfilterswidget.cpp:174
#8 0x000000000063998c in FiltersBase::qt_static_metacall (_o=0x18712d0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7ffc5d320080) at src/gui/qbt_gui_automoc.dir/moc_transferlistfi_HU55MXOLBACKX2.cpp:92
#9 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18712d0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=8, argv=argv@entry=0x7ffc5d320080) at kernel/qobject.cpp:3766
#10 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18712d0, m=m@entry=0x7fed298c6260 <QListWidget::staticMetaObject>, local_signal_index=local_signal_index@entry=8, argv=argv@entry=0x7ffc5d320080) at kernel/qobject.cpp:3628
#11 0x00007fed29485211 in QListWidget::currentRowChanged (this=this@entry=0x18712d0, _t1=<optimized out>) at .moc/moc_qlistwidget.cpp:411
#12 0x00007fed29485b92 in QListWidgetPrivate::_q_emitCurrentItemChanged (this=<optimized out>, current=..., previous=...) at itemviews/qlistwidget.cpp:1128
#13 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18aa7b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d320210) at kernel/qobject.cpp:3766
#14 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18aa7b0, m=m@entry=0x7fed286979e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d320210) at kernel/qobject.cpp:3628
#15 0x00007fed2818cf3a in QItemSelectionModel::currentChanged (this=this@entry=0x18aa7b0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#16 0x00007fed2818d22e in QItemSelectionModel::setCurrentIndex (this=this@entry=0x18aa7b0, index=..., command=..., command@entry=...) at itemmodels/qitemselectionmodel.cpp:1414
#17 0x00007fed29431bac in QAbstractItemView::mousePressEvent (this=0x18712d0, event=<optimized out>) at itemviews/qabstractitemview.cpp:1788
#18 0x00007fed2922671f in QWidget::event (this=this@entry=0x18712d0, event=event@entry=0x7ffc5d3209e0) at kernel/qwidget.cpp:8794
```
Divergence is on `TransferListWidget::applyStatusFilter()`.

**Comment by midenok** [comment]
```c++
#0 TransferListWidget::currentChanged (this=0x197ab70, current=...) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:886
#1 0x000000000063aba1 in TransferListWidget::qt_static_metacall (_o=0x197ab70, _c=QMetaObject::InvokeMetaMethod, _id=37, _a=0x7ffc5d31f730) at src/gui/qbt_gui_automoc.dir/moc_transferlistwi_OC27T367ACJHOU.cpp:284
#2 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18215a0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d31f730) at kernel/qobject.cpp:3766
#3 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18215a0, m=m@entry=0x7fed286979e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d31f730) at kernel/qobject.cpp:3628
#4 0x00007fed2818cf3a in QItemSelectionModel::currentChanged (this=this@entry=0x18215a0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#5 0x00007fed28193469 in QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved (this=0x18505b0, parent=..., start=0, end=11) at itemmodels/qitemselectionmodel.cpp:736
#6 0x00007fed28196029 in QItemSelectionModel::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qitemselectionmodel.cpp:264
#7 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x19452e0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=11, argv=argv@entry=0x7ffc5d31fa60) at kernel/qobject.cpp:3766
#8 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x19452e0, m=m@entry=0x7fed286976a0 <QAbstractItemModel::staticMetaObject>, local_signal_index=local_signal_index@entry=11, argv=argv@entry=0x7ffc5d31fa60) at kernel/qobject.cpp:3628
#9 0x00007fed2817c2be in QAbstractItemModel::rowsAboutToBeRemoved (this=this@entry=0x19452e0, _t1=..., _t2=<optimized out>, _t2@entry=0, _t3=<optimized out>, _t3@entry=11, _t4=...) at .moc/moc_qabstractitemmodel.cpp:610
#10 0x00007fed2818321b in QAbstractItemModel::beginRemoveRows (this=0x19452e0, parent=..., first=0, last=11) at itemmodels/qabstractitemmodel.cpp:2746
#11 0x00007fed281a7b65 in QSortFilterProxyModelPrivate::remove_proxy_interval (emit_signal=true, orient=Qt::Vertical, proxy_parent=..., proxy_end=11, proxy_start=0, proxy_to_source=QVector<int> = {...}, source_to_proxy=QVector<int> = {...}, this=0x1850050) at itemmodels/qsortfilterproxymodel.cpp:584
#12 QSortFilterProxyModelPrivate::remove_source_items (this=this@entry=0x1850050, source_to_proxy=QVector<int> = {...}, proxy_to_source=QVector<int> = {...}, source_items=QVector<int> = {...}, source_parent=..., orient=orient@entry=Qt::Vertical, emit_signal=true) at itemmodels/qsortfilterproxymodel.cpp:565
#13 0x00007fed281a80c2 in QSortFilterProxyModelPrivate::handle_filter_changed (this=this@entry=0x1850050, source_to_proxy=QVector<int> = {...}, proxy_to_source=QVector<int> = {...}, source_parent=..., orient=orient@entry=Qt::Vertical) at itemmodels/qsortfilterproxymodel.cpp:1149
#14 0x00007fed281a8439 in QSortFilterProxyModelPrivate::filter_changed (this=0x1850050, source_parent=...) at itemmodels/qsortfilterproxymodel.cpp:1082
#15 0x00007fed281a8c9a in QSortFilterProxyModel::invalidateFilter() () at itemmodels/qsortfilterproxymodel.cpp:2545
#16 0x0000000000656552 in TransferListSortModel::setStatusFilter (this=0x19452e0, filter=TorrentFilter::Downloading) at /home/midenok/src/qbittorrent/src/gui/transferlistsortmodel.cpp:47
#17 0x000000000062ee0c in TransferListWidget::applyStatusFilter (this=0x197ab70, f=1) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:914
#18 0x000000000061e1ef in StatusFiltersWidget::applyFilter (this=0x18712d0, row=1) at /home/midenok/src/qbittorrent/src/gui/transferlistfilterswidget.cpp:174
#19 0x000000000063998c in FiltersBase::qt_static_metacall (_o=0x18712d0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7ffc5d320080) at src/gui/qbt_gui_automoc.dir/moc_transferlistfi_HU55MXOLBACKX2.cpp:92
#20 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18712d0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=8, argv=argv@entry=0x7ffc5d320080) at kernel/qobject.cpp:3766
#21 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18712d0, m=m@entry=0x7fed298c6260 <QListWidget::staticMetaObject>, local_signal_index=local_signal_index@entry=8, argv=argv@entry=0x7ffc5d320080) at kernel/qobject.cpp:3628
#22 0x00007fed29485211 in QListWidget::currentRowChanged (this=this@entry=0x18712d0, _t1=<optimized out>) at .moc/moc_qlistwidget.cpp:411
#23 0x00007fed29485b92 in QListWidgetPrivate::_q_emitCurrentItemChanged (this=<optimized out>, current=..., previous=...) at itemviews/qlistwidget.cpp:1128
#24 0x00007fed2820f8e5 in QMetaObject::activate (sender=sender@entry=0x18aa7b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d320210) at kernel/qobject.cpp:3766
#25 0x00007fed2820ffb7 in QMetaObject::activate (sender=sender@entry=0x18aa7b0, m=m@entry=0x7fed286979e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffc5d320210) at kernel/qobject.cpp:3628
#26 0x00007fed2818cf3a in QItemSelectionModel::currentChanged (this=this@entry=0x18aa7b0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#27 0x00007fed2818d22e in QItemSelectionModel::setCurrentIndex (this=this@entry=0x18aa7b0, index=..., command=..., command@entry=...) at itemmodels/qitemselectionmodel.cpp:1414
#28 0x00007fed29431bac in QAbstractItemView::mousePressEvent (this=0x18712d0, event=<optimized out>) at itemviews/qabstractitemview.cpp:1788
#29 0x00007fed2922671f in QWidget::event (this=this@entry=0x18712d0, event=event@entry=0x7ffc5d3209e0) at kernel/qwidget.cpp:8794
```

**Comment by midenok** [comment]
### Switch filter
```c++
void TransferListSortModel::setStatusFilter(TorrentFilter::Type filter)
{
    if (m_filter.setType(filter))
        invalidateFilter();
}
```

**Comment by midenok** [comment]
### Current torrent changed via torrent pause
```c++
#0 TransferListWidget::currentChanged (this=0x2cd8c40, current=...) at /home/midenok/src/qbittorrent/src/gui/transferlistwidget.cpp:886
#1 0x000000000063aba1 in TransferListWidget::qt_static_metacall (_o=0x2cd8c40, _c=QMetaObject::InvokeMetaMethod, _id=37, _a=0x7fff33128bb0) at src/gui/qbt_gui_automoc.dir/moc_transferlistwi_OC27T367ACJHOU.cpp:284
#2 0x00007f67b0eb48e5 in QMetaObject::activate (sender=sender@entry=0x2c642a0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fff33128bb0) at kernel/qobject.cpp:3766
#3 0x00007f67b0eb4fb7 in QMetaObject::activate (sender=sender@entry=0x2c642a0, m=m@entry=0x7f67b133c9e0 <QItemSelectionModel::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fff33128bb0) at kernel/qobject.cpp:3628
#4 0x00007f67b0e31f3a in QItemSelectionModel::currentChanged (this=this@entry=0x2c642a0, _t1=..., _t2=...) at .moc/moc_qitemselectionmodel.cpp:487
#5 0x00007f67b0e38469 in QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved (this=0x2d3b970, parent=..., start=0, end=0) at itemmodels/qitemselectionmodel.cpp:736
#6 0x00007f67b0e3b029 in QItemSelectionModel::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qitemselectionmodel.cpp:264
#7 0x00007f67b0eb48e5 in QMetaObject::activate (sender=sender@entry=0x2c444f0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=11, argv=argv@entry=0x7fff33128ee0) at kernel/qobject.cpp:3766
#8 0x00007f67b0eb4fb7 in QMetaObject::activate (sender=sender@entry=0x2c444f0, m=m@entry=0x7f67b133c6a0 <QAbstractItemModel::staticMetaObject>, local_signal_index=local_signal_index@entry=11, argv=argv@entry=0x7fff33128ee0) at kernel/qobject.cpp:3628
#9 0x00007f67b0e212be in QAbstractItemModel::rowsAboutToBeRemoved (this=this@entry=0x2c444f0, _t1=..., _t2=<optimized out>, _t2@entry=0, _t3=<optimized out>, _t3@entry=0, _t4=...) at .moc/moc_qabstractitemmodel.cpp:610
#10 0x00007f67b0e2821b in QAbstractItemModel::beginRemoveRows (this=0x2c444f0, parent=..., first=0, last=0) at itemmodels/qabstractitemmodel.cpp:2746
#11 0x00007f67b0e4cb65 in QSortFilterProxyModelPrivate::remove_proxy_interval (emit_signal=true, orient=Qt::Vertical, proxy_parent=..., proxy_end=0, proxy_start=0, proxy_to_source=QVector<int> = {...}, source_to_proxy=QVector<int> = {...}, this=0x2c4c160) at itemmodels/qsortfilterproxymodel.cpp:584
#12 QSortFilterProxyModelPrivate::remove_source_items (this=this@entry=0x2c4c160, source_to_proxy=QVector<int> = {...}, proxy_to_source=QVector<int> = {...}, source_items=QVector<int> = {...}, source_parent=..., orient=orient@entry=Qt::Vertical, emit_signal=true) at itemmodels/qsortfilterproxymodel.cpp:565
#13 0x00007f67b0e4e311 in QSortFilterProxyModelPrivate::_q_sourceDataChanged (this=0x2c4c160, source_top_left=..., source_bottom_right=..., roles=empty QVector<int>) at itemmodels/qsortfilterproxymodel.cpp:1206
#14 0x00007f67b0e4f3f8 in QSortFilterProxyModel::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qsortfilterproxymodel.cpp:204
#15 0x00007f67b0eb48e5 in QMetaObject::activate (sender=0x2c77ff0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fff33129300) at kernel/qobject.cpp:3766
#16 0x00007f67b0eb4fb7 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7f67b133c6a0 <QAbstractItemModel::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fff33129300) at kernel/qobject.cpp:3628
#17 0x00007f67b0e20ffc in QAbstractItemModel::dataChanged (this=<optimized out>, _t1=..., _t2=..., _t3=...) at .moc/moc_qabstractitemmodel.cpp:568
#18 0x000000000065368f in TorrentModel::handleTorrentStatusUpdated (this=0x2c77ff0, torrent=0x2c9e5f0) at /home/midenok/src/qbittorrent/src/gui/torrentmodel.cpp:307
#19 0x000000000063922c in TorrentModel::qt_static_metacall (_o=0x2c77ff0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fff331295a0) at src/gui/qbt_gui_automoc.dir/moc_torrentmodel_U6CBPMSH5TELAR.cpp:88
#20 0x00007f67b0eb48e5 in QMetaObject::activate (sender=0x2b11340, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3766
#21 0x000000000052b52f in BitTorrent::Session::torrentPaused (this=0x2b11340, _t1=0x2c9e5f0) at /home/midenok/src/qbittorrent/build/src/base/qbt_base_automoc.dir/moc_session_V3MD6UR47GUQY7.cpp:634
#22 0x0000000000487146 in BitTorrent::Session::handleTorrentPaused (this=0x2b11340, torrent=0x2c9e5f0) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:2881
#23 0x00000000004bb8b0 in BitTorrent::TorrentHandle::handleTorrentPausedAlert (this=0x2c9e5f0, p=0x7f67900c9020) at /home/midenok/src/qbittorrent/src/base/bittorrent/torrenthandle.cpp:1464
#24 0x00000000004bd6ab in BitTorrent::TorrentHandle::handleAlert (this=0x2c9e5f0, a=0x7f67900c9020) at /home/midenok/src/qbittorrent/src/base/bittorrent/torrenthandle.cpp:1651
#25 0x000000000048375e in BitTorrent::Session::dispatchTorrentAlert (this=0x2b11340, a=0x7f67900c9020) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3300
#26 0x000000000048a5f7 in BitTorrent::Session::handleAlert (this=0x2b11340, a=0x7f67900c9020) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3241
#27 0x000000000048a3d3 in BitTorrent::Session::readAlerts (this=0x2b11340) at /home/midenok/src/qbittorrent/src/base/bittorrent/session.cpp:3216
#28 0x000000000052a7e8 in BitTorrent::Session::qt_static_metacall (_o=0x2b11340, _c=QMetaObject::InvokeMetaMethod, _id=33, _a=0x7f678400b6b0) at /home/midenok/src/qbittorrent/build/src/base/qbt_base_automoc.dir/moc_session_V3MD6UR47GUQY7.cpp:303
#29 0x00007f67b0eb5452 in QObject::event (this=0x2b11340, e=<optimized out>) at kernel/qobject.cpp:1246
```
 #### Important
```c++
#18 0x000000000065368f in TorrentModel::handleTorrentStatusUpdated (this=0x2c77ff0, torrent=0x2c9e5f0) at /home/midenok/src/qbittorrent/src/gui/torrentmodel.cpp:307
```
```c++
void TorrentModel::handleTorrentStatusUpdated(BitTorrent::TorrentHandle *const torrent)
{
    const int row = m_torrents.indexOf(torrent);
    if (row >= 0)
        emit dataChanged(index(row, 0), index(row, columnCount() - 1));
}
```
